name: "Update Changelog"

on:
  release:
    types: [released, prereleased]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Determine branch
        id: branch
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "branch=development" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.branch.outputs.branch }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ steps.branch.outputs.branch }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
